networks:
  reservations:

services:
  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - '8080:8080'
      # - '443:443'
      # - '443:443/udp'
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/site:/srv
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - reservations

volumes:
  caddy_data:
  caddy_config:
